services:
  app:
    build:
      context: ../../
      dockerfile: zarf/docker/dockerfile.service
    restart: always
    ports:
      - '3000:3000'
      - '4000:4000'
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
